repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
        #args: # arguments to bypass Markdown files
        #  - "--markdown-linebreak-ext=md"
      - id: check-yaml
      - id: check-json
      # flake8
      - id: flake8
        args: # arguments to configure flake8
        # Override default length=79
          - "--max-line-length=199"
      - id: check-toml
      - id: check-xml
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: '' ## Add when needs
#    hooks:
#      - id: mypy
